# Generated by Django 4.2.3 on 2023-08-09 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('image', models.TextField()),
                ('instructions', models.TextField()),
                ('category', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('measurement', models.CharField()),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='meal_app.meals')),
            ],
        ),
    ]
