# Generated by Django 4.2.4 on 2023-08-11 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='meal',
        ),
        migrations.CreateModel(
            name='Meal_ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='meal_app.meal')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal', to='meal_app.meal')),
            ],
        ),
    ]
