# Generated by Django 4.2.4 on 2023-08-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_app', '0002_alter_meal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
