# Generated by Django 4.2.4 on 2023-08-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_app', '0003_meal_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
