# Generated by Django 4.2.4 on 2023-08-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_app', '0003_alter_meal_ingredient_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, default='meal_images/default.png', null=True, upload_to='meal_images/'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
