# Generated by Django 4.2.4 on 2023-08-11 21:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal_app', '0002_remove_ingredient_meal_meal_ingredient'),
        ('meal_plan_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal_plan',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='meal_plan',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='meal_plan',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='meal_plan',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='meal_plan',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='meal_plan',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='meal_plan',
            name='wednesday',
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2023, 8, 11))),
                ('daily_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_meal', to='meal_app.meal')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan', to='meal_plan_app.meal_plan')),
            ],
        ),
    ]
