# Generated by Django 4.2.4 on 2023-08-21 02:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan_app', '0002_alter_day_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 21)),
        ),
    ]
