# Generated by Django 4.2.4 on 2023-08-13 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plan_app', '0003_alter_day_date_alter_day_meal_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 13)),
        ),
    ]
