# Generated by Django 4.2.4 on 2023-08-14 18:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal_app', '0003_alter_meal_ingredient_ingredient_and_more'),
        ('meal_plan_app', '0004_alter_day_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='daily_meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_meal', to='meal_app.meal'),
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 14)),
        ),
    ]
