# Generated by Django 4.2.4 on 2023-08-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='user_images/default.png', null=True, upload_to='user_images/'),
        ),
    ]
